"""empty message

Revision ID: 1bd4cf553958
Revises:
Create Date: 2023-07-05 10:17:31.338599

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '1bd4cf553958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE categories SET SCHEMA {SCHEMA};")
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('about', sa.String(length=500), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE subcategories SET SCHEMA {SCHEMA};")
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE threads SET SCHEMA {SCHEMA};")
    op.create_table('liked_threads',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'thread_id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE liked_threads SET SCHEMA {SCHEMA};")
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE posts SET SCHEMA {SCHEMA};")
    op.create_table('thread_categories',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], )
    )
    if environment == "production":
        op.execute(f"ALTER TABLE thread_categories SET SCHEMA {SCHEMA};")
    op.create_table('thread_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threadId', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['threadId'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE thread_images SET SCHEMA {SCHEMA};")
    op.create_table('thread_sub_categories',
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_category_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], )
    )
    if environment == "production":
        op.execute(f"ALTER TABLE thread_sub_categories SET SCHEMA {SCHEMA};")
    op.create_table('post_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postId', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['postId'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE post_images SET SCHEMA {SCHEMA};")
    op.create_table('reply',
    sa.Column('replyer', sa.Integer(), nullable=False),
    sa.Column('replied', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['replied'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['replyer'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('replyer', 'replied')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE reply SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('post_images')
    op.drop_table('thread_sub_categories')
    op.drop_table('thread_images')
    op.drop_table('thread_categories')
    op.drop_table('posts')
    op.drop_table('liked_threads')
    op.drop_table('threads')
    op.drop_table('subcategories')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
